// <auto-generated />
using System;
using MetekLisansApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetekLisansApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250324114554_fixProjeDurumlari")]
    partial class fixProjeDurumlari
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MetekLisansApp.Models.Entities.BakimAnlasmasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BakimAnlasmasi");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.BakimPaketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BakimPaketi");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.Ekran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EkranNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Ekranlar");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.Lisans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LisansBitisTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("LisansKodu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LisansVerilmeTarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("OlusturanUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeciliDegerler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lisanslar");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.LisansSure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LisansSure");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiraNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Menuler");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.ProjeDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnlasmaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BakimPaketId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BakimSozlesmeBitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LisansAtansinmi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LisansSureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MevcutLisans")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasColumnType("TEXT");

                    b.Property<int>("SahipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnlasmaId");

                    b.HasIndex("BakimPaketId");

                    b.HasIndex("FirmaId");

                    b.HasIndex("LisansSureId");

                    b.HasIndex("SahipId");

                    b.HasIndex("StatuId");

                    b.ToTable("ProjeDurumu");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.Sahip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sahip");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.Statu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statu");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.Ekran", b =>
                {
                    b.HasOne("MetekLisansApp.Models.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("MetekLisansApp.Models.Entities.ProjeDurumu", b =>
                {
                    b.HasOne("MetekLisansApp.Models.Entities.BakimAnlasmasi", "BakimAnlasmasi")
                        .WithMany()
                        .HasForeignKey("AnlasmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetekLisansApp.Models.Entities.BakimPaketi", "BakimPaketi")
                        .WithMany()
                        .HasForeignKey("BakimPaketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetekLisansApp.Models.Entities.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetekLisansApp.Models.Entities.LisansSure", "LisansSure")
                        .WithMany()
                        .HasForeignKey("LisansSureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetekLisansApp.Models.Entities.Sahip", "Sahip")
                        .WithMany()
                        .HasForeignKey("SahipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetekLisansApp.Models.Entities.Statu", "Statu")
                        .WithMany()
                        .HasForeignKey("StatuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BakimAnlasmasi");

                    b.Navigation("BakimPaketi");

                    b.Navigation("Firma");

                    b.Navigation("LisansSure");

                    b.Navigation("Sahip");

                    b.Navigation("Statu");
                });
#pragma warning restore 612, 618
        }
    }
}
